name: psypy
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - freetype=2.12.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.14
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=24.0
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - pytz=2024.1
  - seaborn=0.13.2
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - unicodedata2=15.1.0
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - ipython==8.24.0
      - openpyxl==3.1.2
      - psychopy==2024.1.4
      - psychopy-pyo==0.0.1
      - psychopy-sounddevice==0.0.1
      - psychtoolbox==3.0.19.0
      - slab==1.5.1
      - soundcard==0.4.3
      - sounddevice==0.5.0
      - soundfile==0.12.1
