logging:
  level: DEBUG  # choose which logging level you want

filepaths:  # soome relevant filepaths
  project: C:/PycharmProjects/psychopy-experiments
  stimuli: C:/PycharmProjects/psychopy-experiments/stimuli
  sequences: C:/PycharmProjects/psychopy-experiments/SPACEPRIME/sequences

session:  # these params are relevant for the generation of the possible combinations excel sheet or trial sequence
  distractor_type: high  # can be low or high
  n_locations: 3
  n_digits: 9
  n_trials: 225  # number of trials per block
  stimulus_duration: 0.25
  response_duration: 1.25
  iti: 1.0
  n_blocks: 8
  level: 50  # not the final volume but choose this to avoid clipping audio data
  samplerate: 44100
  timing: seconds

preferences:  # set some preferences
  general:
    audioLib: sounddevice  # define sound device. Possible options can be drawn from PsychoPy homepage
    units: deg

window:
  size: [1440, 900]
  pos: [0, 0]
  color: [0, 0, 0]
  fullscr: True
  #winType: pyglet
  waitBlanking: True
  screen: 0

monitor:
  name: default
  width: 50  # in cm
  distance: 80  # in cm
  gamma: 1

mouse:
  visible: False

eyetracker:
  model: eyelink
  CNUM: 9
  MIN_CALIB_FIX: 1000
