logging:
  level: DEBUG  # choose which logging level you want --> ONLY FOR PSYCHOPY EXPERIMENT; NOT APPLICABLE TO TRIAL SEQUENCES

filepaths:  # soome relevant filepaths
  project: C:/PycharmProjects/psychopy-experiments
  stimuli: C:/PycharmProjects/psychopy-experiments/stimuli
  sequences: C:/PycharmProjects/psychopy-experiments/SPACEPRIME/sequences

session:  # these params are relevant for the generation of the possible combinations excel sheet or trial sequence
  distractor_type: high  # can be low or high
  n_locations: 3
  n_digits: 9
  n_trials: 225  # number of trials per block
  stimulus_duration: 0.25
  response_duration: 1.25
  iti: 1.0
  n_blocks: 8
  level: 50  # not the final volume but choose this to avoid clipping audio data
  samplerate: 44100
  timing: seconds
  response_device: mouse  # can be mouse or keypad
  fixation_type: circle  # can be circle or cross

numpad:
  digits: [1, 2, 3, 4, 5, 6, 7, 8, 9]
  width: 15
  height: 15
  spacing: 0

trial_sequence:
  conditions: [1, 2, 3]  # C, NP and PP
  prop_c: 0.6  # 60 % C
  prop_np: 0.2  # 20 % NP
  prop_pp: 0.2  #  20 % PP
  rule_violation_factor: 1000
  num_generations: 5000  # 3000 iterations for genetic algorithm
  num_parents_mating: 10  #
  sol_per_pop: 200  # 200 children per generation
  keep_parents: 2  # Elitism
  mutation_percent_genes: 5

preferences:  # set some preferences
  general:
    audioLib: sounddevice  # define sound device. Possible options can be drawn from PsychoPy homepage
    units: deg

window:
  size: [1440, 900]
  pos: [0, 0]
  color: [0, 0, 0]
  fullscr: True
  #winType: pyglet
  waitBlanking: True
  screen: 0

monitor:
  name: default
  width: 50  # in cm
  distance: 80  # in cm
  gamma: 1

mouse:
  visible: True

eyetracker:
  model: eyelink
  CNUM: 9
  MIN_CALIB_FIX: 1000
