name: psypy
channels:
  - defaults
dependencies:
  - blas=1.0
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - freetype=2.12.1
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libffi=3.4.4
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.4.0
  - openssl=3.0.14
  - pandas=2.2.2
  - pillow=10.3.0
  - pip=24.0
  - python=3.10.14
  - python-dateutil=2.9.0post0
  - pytz=2024.1
  - seaborn=0.13.2
  - six=1.16.0
  - sqlite=3.45.3
  - tbb=2021.8.0
  - tk=8.6.14
  - unicodedata2=15.1.0
  - vc=14.2
  - vs2015_runtime=14.29.30133
  - wheel=0.43.0
  - xz=5.4.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - arabic-reshaper==3.0.0
      - asttokens==2.4.1
      - astunparse==1.6.3
      - audioread==3.0.1
      - bbtkv2==0.3
      - beautifulsoup4==4.12.3
      - blosc2==2.6.2
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - cloudpickle==3.0.0
      - colorama==0.4.6
      - contourpy==1.2.1
      - cryptography==42.0.7
      - cycler==0.12.1
      - decorator==5.1.1
      - dill==0.3.8
      - dukpy==0.3.1
      - elementpath==4.4.0
      - esprima==4.0.1
      - et-xmlfile==1.1.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - ffpyplayer==4.5.1
      - fonttools==4.52.4
      - freetype-py==2.4.0
      - future==1.0.0
      - gevent==24.2.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - greenlet==3.0.3
      - html2text==2024.2.26
      - idna==3.7
      - imageio==2.34.1
      - imageio-ffmpeg==0.4.9
      - ipython==8.24.0
      - javascripthon==0.12
      - jedi==0.19.1
      - joblib==1.4.2
      - json-tricks==3.17.3
      - kiwisolver==1.4.5
      - lazy-loader==0.4
      - levenshtein==0.25.1
      - librosa==0.10.2.post1
      - llvmlite==0.42.0
      - markdown-it-py==3.0.0
      - matplotlib==3.9.0
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - msgpack==1.0.8
      - msgpack-numpy==0.4.8
      - ndindex==1.8
      - numba==0.59.1
      - numexpr==2.10.0
      - opencv-python==4.9.0.80
      - openpyxl==3.1.2
      - pa-ringbuffer==0.1.4
      - packaging==24.0
      - parso==0.8.4
      - platformdirs==4.2.2
      - pooch==1.8.1
      - prompt-toolkit==3.0.45
      - psutil==5.9.8
      - psychopy==2024.1.4
      - psychopy-pyo==0.0.1
      - psychopy-sounddevice==0.0.1
      - psychtoolbox==3.0.19.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pycparser==2.22
      - pygad==3.3.1
      - pyglet==1.4.11
      - pygments==2.18.0
      - pyo==1.0.5
      - pyparallel==0.2.2
      - pyparsing==3.1.2
      - pypi-search==2.0
      - pypiwin32==223
      - pyqt5==5.15.10
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.13.0
      - pyqt6==6.7.0
      - pyqt6-qt6==6.7.0
      - pyqt6-sip==13.6.0
      - pyserial==3.5
      - python-bidi==0.4.2
      - python-constraint==1.4.0
      - python-gitlab==4.6.0
      - python-levenshtein==0.25.1
      - python-vlc==3.0.11115
      - pywin32==306
      - pywinhook==1.6.2
      - pyyaml==6.0.1
      - pyzmq==26.0.3
      - questplus==2023.1
      - rapidfuzz==3.9.6
      - requests==2.32.2
      - requests-toolbelt==1.0.0
      - rtmixer==0.1.7
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - setuptools==66.1.1
      - slab==1.5.1
      - smmap==5.0.1
      - soundcard==0.4.3
      - sounddevice==0.5.0
      - soundfile==0.12.1
      - soupsieve==2.5
      - soxr==0.3.7
      - stack-data==0.6.3
      - tables==3.9.2
      - tabulate==0.9.0
      - threadpoolctl==3.5.0
      - toml==0.10.2
      - traitlets==5.14.3
      - typing-extensions==4.12.0
      - tzdata==2024.1
      - ujson==5.10.0
      - urllib3==2.2.1
      - wcwidth==0.2.13
      - websockets==12.0
      - wxpython==4.2.1
      - xarray==2024.5.0
      - xlsxwriter==3.2.0
      - xmlschema==3.3.1
      - zope-event==5.0
      - zope-interface==6.4.post2
