logging:
  level: DEBUG

filepaths:
  project: C:/PycharmProjects/psychopy-experiments
  stimuli: C:/PycharmProjects/psychopy-experiments/stimuli
  sequences: C:/PycharmProjects/psychopy-experiments/WP1/sequences

session:
  distractor_type: high  # can be low or high
  n_locations: 3
  n_digits: 9
  n_trials: 300  # number of trials per block
  stimulus_duration: 0.25
  response_duration: 1.0
  iti: 1.5
  n_blocks: 6
  level: 65
  samplerate: 44100
  timing: seconds

preferences:
  general:
    audioLib: sounddevice
    units: deg

window:
  size: [1440, 900]
  pos: [0, 0]
  color: [0, 0, 0]
  fullscr: True
  #winType: pyglet
  waitBlanking: True
  screen: 0

monitor:
  name: default
  width: 50  # in cm
  distance: 80  # in cm
  gamma: 1

mouse:
  visible: False

eyetracker:
  model: eyelink
  CNUM: 9
  MIN_CALIB_FIX: 1000
